[package]
name = "mach_rs"
version = "0.1.0"
edition = "2024"

[dependencies]
rust_decimal = "1.39.0"
rust_decimal_macros = "1.39.0"

[dev-dependencies]
criterion = "0.8.1"

[[bench]]
name = "benchmark"
harness = false